# Generated by Django 3.1.5 on 2021-11-27 01:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTitulos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lei', models.CharField(max_length=20)),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'titulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artigo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capitulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel2',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel3',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('nivel2', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel4',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('nivel2', models.TextField(blank=True, null=True)),
                ('nivel3', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='q_c_q',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('assunto', models.TextField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('banca', models.TextField(blank=True, null=True)),
                ('orgao', models.TextField(blank=True, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('questao', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('gabarito', models.TextField(blank=True, null=True)),
                ('comando', models.TextField(blank=True, null=True)),
                ('texto_item', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'q_c_q',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsecao',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.IntegerField(blank=True, null=True)),
                ('sec', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsecao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questoes_feitas', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='uploads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('show_name', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=150)),
                ('photo', models.FileField(upload_to='anexo/')),
                ('endereco', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
