# Generated by Django 3.1.5 on 2021-09-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='titulos',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('lei', models.CharField(default='', max_length=20)),
                ('texto', models.TextField()),
            ],
        ),
    ]
