# Generated by Django 3.1.5 on 2021-11-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
    ]
