# Generated by Django 3.1.5 on 2021-11-27 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211127_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('show_name', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=150)),
                ('photo', models.FileField(upload_to='anexo/')),
                ('endereco', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexo2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Anexo',
        ),
    ]
