# Generated by Django 3.1.5 on 2021-11-27 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211127_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexo2', to=settings.AUTH_USER_MODEL),
        ),
    ]
