# Generated by Django 3.1.5 on 2021-10-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_questao'),
    ]

    operations = [
        migrations.CreateModel(
            name='q_c_q',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('assunto', models.TextField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('banca', models.TextField(blank=True, null=True)),
                ('orgao', models.TextField(blank=True, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('questao', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('gabarito', models.TextField(blank=True, null=True)),
                ('comando', models.TextField(blank=True, null=True)),
                ('texto_item', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'q_c_q',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
